/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author shanu
 */
public class Profile extends javax.swing.JFrame {

    /**
     * Creates new form Profile
     */
    
    List<String> data2 = new ArrayList<>();
    public Profile(List<String> data) {
        data2 = data;
        initComponents();
        Tname.setText(data2.get(1));
        Tadhaar.setText(data2.get(2));
        Tphone.setText(data2.get(3));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_edit_name = new javax.swing.JButton();
        Tamount = new javax.swing.JTextField();
        Btn_edit_adhaar = new javax.swing.JButton();
        TOldPassword = new javax.swing.JTextField();
        Btn_edit_phone = new javax.swing.JButton();
        Lname = new javax.swing.JLabel();
        Btn_deposit = new javax.swing.JButton();
        Ladhaar = new javax.swing.JLabel();
        Btn_change_password = new javax.swing.JButton();
        Lphone = new javax.swing.JLabel();
        LNewPassword = new javax.swing.JLabel();
        Lamount = new javax.swing.JLabel();
        TNewPassword = new javax.swing.JTextField();
        LOldPassword = new javax.swing.JLabel();
        BtnBack = new javax.swing.JButton();
        Tname = new javax.swing.JTextField();
        Tadhaar = new javax.swing.JTextField();
        Tphone = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(400, 200, 0, 0));
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });

        Btn_edit_name.setText("Edit");
        Btn_edit_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_edit_nameActionPerformed(evt);
            }
        });

        Tamount.setFont(new java.awt.Font("Segoe UI Light", 3, 14)); // NOI18N
        Tamount.setText("Minimum Deposit Rs.50");
        Tamount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TamountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TamountFocusLost(evt);
            }
        });
        Tamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TamountActionPerformed(evt);
            }
        });

        Btn_edit_adhaar.setText("Edit");
        Btn_edit_adhaar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_edit_adhaarActionPerformed(evt);
            }
        });

        TOldPassword.setFont(new java.awt.Font("Segoe UI Light", 3, 14)); // NOI18N

        Btn_edit_phone.setText("Edit");
        Btn_edit_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_edit_phoneActionPerformed(evt);
            }
        });

        Lname.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        Lname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lname.setText("Name :");

        Btn_deposit.setText("Deposit");
        Btn_deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_depositActionPerformed(evt);
            }
        });

        Ladhaar.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        Ladhaar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Ladhaar.setText("Adhaar No : ");

        Btn_change_password.setText("Change");
        Btn_change_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_change_passwordActionPerformed(evt);
            }
        });

        Lphone.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        Lphone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lphone.setText("Phone no :");

        LNewPassword.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        LNewPassword.setText("New Password :");

        Lamount.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        Lamount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lamount.setText("Add Amount :");

        TNewPassword.setFont(new java.awt.Font("Segoe UI Light", 3, 14)); // NOI18N
        TNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNewPasswordActionPerformed(evt);
            }
        });

        LOldPassword.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        LOldPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LOldPassword.setText("Old Password :");

        BtnBack.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        BtnBack.setText("RE-LOGIN");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        Tname.setEditable(false);
        Tname.setFont(new java.awt.Font("Segoe UI Light", 3, 14)); // NOI18N
        Tname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TnameActionPerformed(evt);
            }
        });

        Tadhaar.setEditable(false);
        Tadhaar.setFont(new java.awt.Font("Segoe UI Light", 3, 14)); // NOI18N
        Tadhaar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TadhaarActionPerformed(evt);
            }
        });

        Tphone.setEditable(false);
        Tphone.setFont(new java.awt.Font("Segoe UI Light", 3, 14)); // NOI18N
        Tphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TphoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnBack)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Lamount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lphone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LOldPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Ladhaar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LNewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Tadhaar)
                            .addComponent(Tname)
                            .addComponent(Tphone)
                            .addComponent(Tamount, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(TOldPassword)
                            .addComponent(TNewPassword))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Btn_edit_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_edit_adhaar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_edit_phone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_deposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_change_password, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Tname, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn_edit_name, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_edit_adhaar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Ladhaar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Tadhaar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Tphone, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lphone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_edit_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lamount, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tamount, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_deposit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TOldPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_change_password, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BtnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_edit_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_edit_nameActionPerformed
        // TODO add your handling code here:

        if(Tname.getText().equals("")){
            JOptionPane.showMessageDialog(new JFrame(), "please Enter data", "Dialog",JOptionPane.ERROR_MESSAGE);
            setVisible(false);
            setVisible(true);
            Tname.setText("");
        }

        else if(Btn_edit_name.getText() == "Edit"){
            Btn_edit_name.setText("Change");
            Tname.setEditable(true);
            Tname.requestFocusInWindow();
            Tname.requestFocus();
            
        }
        else if(Btn_edit_name.getText()== "Change"){
            Btn_edit_name.setText("Edit");
            Tname.setEditable(false);
            
            DbAccess db = new DbAccess();
            db.UpdateName(data2.get(2), Tname.getText());
        }
    }//GEN-LAST:event_Btn_edit_nameActionPerformed

    private void TamountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TamountFocusGained
        // TODO add your handling code here:
        if(Tamount.getText().equals("Minimum Deposit Rs.50")){
            Tamount.setText("");
        }
    }//GEN-LAST:event_TamountFocusGained

    private void TamountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TamountFocusLost
        // TODO add your handling code here:
        if(Tamount.getText().equals("")){
            Tamount.setText("Minimum Deposit Rs.50");
        }
    }//GEN-LAST:event_TamountFocusLost

    private void TamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TamountActionPerformed

    private void Btn_edit_adhaarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_edit_adhaarActionPerformed
        // TODO add your handling code here:

        if(Tadhaar.getText().equals("")){
            JOptionPane.showMessageDialog(new JFrame(), "please Enter data", "Dialog",JOptionPane.ERROR_MESSAGE);
            setVisible(false);
            setVisible(true);
            Tadhaar.setText("");
        }
        else if(Btn_edit_adhaar.getText().equals("Edit")){
            Btn_edit_adhaar.setText("Change");
            Tadhaar.setEditable(true);
            Tadhaar.requestFocusInWindow();
            Tadhaar.requestFocus();
        }
        else if(Btn_edit_adhaar.getText().equals("Change")){
            Btn_edit_adhaar.setText("Edit");
            Tadhaar.setEditable(false);
            
            DbAccess db = new DbAccess();
            db.UpdateName(data2.get(3), Tadhaar.getText());
        }
    }//GEN-LAST:event_Btn_edit_adhaarActionPerformed

    private void Btn_edit_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_edit_phoneActionPerformed
        // TODO add your handling code here:

        if(Tphone.getText().equals("")){
            JOptionPane.showMessageDialog(new JFrame(), "please Enter data", "Dialog",JOptionPane.ERROR_MESSAGE);
            setVisible(false);
            setVisible(true);
            Tphone.setText("");
        }
        else if(Btn_edit_phone.getText() == "Edit"){
            Btn_edit_phone.setText("Change");
            Tphone.setEditable(true);
            Tphone.requestFocusInWindow();
            Tphone.requestFocus();

        }
        else if(Btn_edit_phone.getText()== "Change"){
            Btn_edit_phone.setText("Edit");
            Tphone.setEditable(false);
            
            
            DbAccess db = new DbAccess();
            db.UpdatePhone(data2.get(2), Tphone.getText());

        }
    }//GEN-LAST:event_Btn_edit_phoneActionPerformed

    private void Btn_depositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_depositActionPerformed
        // TODO add your handling code here:
        if(Tamount.getText().equals("")){
            JOptionPane.showMessageDialog(new JFrame(), "please Enter data", "Dialog",JOptionPane.ERROR_MESSAGE);
            setVisible(false);
            setVisible(true);

        }
        if(Integer.parseInt(Tamount.getText()) < 50){
            JOptionPane.showMessageDialog(new JFrame(), "Amount should be grater then 50", "Warning",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_Btn_depositActionPerformed

    private void Btn_change_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_change_passwordActionPerformed
        // TODO add your handling code here:

        if(TNewPassword.getText().equals("")&& TOldPassword.getText().equals("")){
            JOptionPane.showMessageDialog(new JFrame(), "please Enter password", "Dialog",JOptionPane.ERROR_MESSAGE);
        }

        else if(TOldPassword.getText().equals(data2.get(5))){
            
            
            Btn_change_password.setText("Done!!!");
            
            DbAccess db = new DbAccess();
            db.UpdatePass(data2.get(2), TNewPassword.getText());
        }
        else{
            JOptionPane.showMessageDialog(new JFrame(), "Old password is wrong", "Dialog",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_Btn_change_passwordActionPerformed

    private void TNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNewPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNewPasswordActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BtnBackActionPerformed

    private void TnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TnameActionPerformed
        // TODO add your handling code here:
        //        Tname

    }//GEN-LAST:event_TnameActionPerformed

    private void TadhaarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TadhaarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TadhaarActionPerformed

    private void TphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TphoneActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                List<String> lis = new ArrayList<String>();
                lis.add("Shaanu");
                lis.add("123");
                lis.add("0988");
                lis.add("PASS");
//                new Profile(lis).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton Btn_change_password;
    private javax.swing.JButton Btn_deposit;
    private javax.swing.JButton Btn_edit_adhaar;
    private javax.swing.JButton Btn_edit_name;
    private javax.swing.JButton Btn_edit_phone;
    private javax.swing.JLabel LNewPassword;
    private javax.swing.JLabel LOldPassword;
    private javax.swing.JLabel Ladhaar;
    private javax.swing.JLabel Lamount;
    private javax.swing.JLabel Lname;
    private javax.swing.JLabel Lphone;
    private javax.swing.JTextField TNewPassword;
    private javax.swing.JTextField TOldPassword;
    private javax.swing.JTextField Tadhaar;
    private javax.swing.JTextField Tamount;
    private javax.swing.JTextField Tname;
    private javax.swing.JTextField Tphone;
    // End of variables declaration//GEN-END:variables
}
