/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author shanu
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    
//    String Acount[] = new String[5];
    ArrayList<String> Account = new ArrayList<>();
    public Registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lname = new javax.swing.JLabel();
        Ladhaar = new javax.swing.JLabel();
        Lphone = new javax.swing.JLabel();
        Lamount = new javax.swing.JLabel();
        Lpassword = new javax.swing.JLabel();
        Tname = new javax.swing.JTextField();
        Tadhaar = new javax.swing.JTextField();
        Tphone = new javax.swing.JTextField();
        Tamount = new javax.swing.JTextField();
        Tpassword = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register New Account");
        setBounds(new java.awt.Rectangle(400, 200, 0, 0));

        Lname.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        Lname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lname.setText("Name :");

        Ladhaar.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        Ladhaar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Ladhaar.setText("Adhaar No : ");

        Lphone.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        Lphone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lphone.setText("Phone no :");

        Lamount.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        Lamount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lamount.setText("Amount :");

        Lpassword.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        Lpassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lpassword.setText("Password :");

        Tname.setFont(new java.awt.Font("Segoe UI Light", 3, 14)); // NOI18N
        Tname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TnameActionPerformed(evt);
            }
        });

        Tadhaar.setFont(new java.awt.Font("Segoe UI Light", 3, 14)); // NOI18N
        Tadhaar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TadhaarActionPerformed(evt);
            }
        });

        Tphone.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        Tphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TphoneActionPerformed(evt);
            }
        });

        Tamount.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        Tamount.setText("Minimum Rs.100");
        Tamount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TamountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TamountFocusLost(evt);
            }
        });
        Tamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TamountActionPerformed(evt);
            }
        });

        Tpassword.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N

        btnRegister.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Lamount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lphone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lpassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Ladhaar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Tadhaar)
                            .addComponent(Tname)
                            .addComponent(Tphone)
                            .addComponent(Tamount, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(Tpassword)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tname, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ladhaar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tadhaar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Tphone, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lphone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lamount, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tamount, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TnameActionPerformed
        // TODO add your handling code here:
//        Tname
    }//GEN-LAST:event_TnameActionPerformed

    private void TadhaarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TadhaarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TadhaarActionPerformed

    private void TphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TphoneActionPerformed

    private void TamountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TamountFocusGained
        // TODO add your handling code here:
        if(Tamount.getText().equals("Minimum Rs.100")){
            Tamount.setText("");
        }
    }//GEN-LAST:event_TamountFocusGained

    private void TamountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TamountFocusLost
        // TODO add your handling code here:
        if(Tamount.getText().equals("")){
            Tamount.setText("Minimum Rs.100");
        }
    }//GEN-LAST:event_TamountFocusLost

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        if(Tname.getText().equals("") && Tadhaar.getText().equals("") && Tphone.getText().equals("") && Tamount.getText().equals("") && Tpassword.getText().equals("")){
            JOptionPane.showMessageDialog(new JFrame(), "Please fill the details", "Dialog",JOptionPane.ERROR_MESSAGE);
            System.out.println(Tname.getText().equals(""));
            System.out.println(Tadhaar.getText().equals(""));
            System.out.println(Tphone.getText().equals(""));
            System.out.println(Tamount.getText().equals(""));
            System.out.println(Tpassword.getText().equals(""));
            
            
        }
        else if(Integer.parseInt(Tamount.getText()) < 100){
            JOptionPane.showMessageDialog(new JFrame(), "Amount should be more then 100rs", "Dialog",JOptionPane.ERROR_MESSAGE);
            Tamount.setText("Minimum Rs.100");
        }
        else{
            
            Account.add(Tname.getText().toLowerCase());
            Account.add(Tadhaar.getText().toLowerCase());
            Account.add(Tphone.getText().toLowerCase());
            Account.add(Tamount.getText().toLowerCase());
            Account.add(Tpassword.getText());
            
            System.out.println(Account);
            dispose();
            DbAccess db = new DbAccess();
            db.NewUser(Account);
            
            Login login = new Login();
            login.setVisible(true);
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void TamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TamountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ladhaar;
    private javax.swing.JLabel Lamount;
    private javax.swing.JLabel Lname;
    private javax.swing.JLabel Lpassword;
    private javax.swing.JLabel Lphone;
    private javax.swing.JTextField Tadhaar;
    private javax.swing.JTextField Tamount;
    private javax.swing.JTextField Tname;
    private javax.swing.JTextField Tpassword;
    private javax.swing.JTextField Tphone;
    private javax.swing.JButton btnRegister;
    // End of variables declaration//GEN-END:variables
}
